- README.md
Added GitHub tests badge in README.md
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
> Added GitHub tests badge

- src/client/pool/dynamic_pricing_config.py
- src/client/pool/dynamic_pricing_config.pyi
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
> Fixed reward_per_assignment field in DynamicPricingConfig

- src/client/__init__.py
fix a problem with Task and TaskSuite adding
> toloka-kit-0.1.5

- .github/workflows/tests.yml
- setup.py
- src/client/primitives/base.py
- src/client/primitives/base.pyi
- src/streaming/cursor.py
- tox.ini
Fixes issue https://github.com/Toloka/toloka-kit/issues/37
> Downgrade from attrs>=21.2.0 to attrs>=20.3.0

- CHANGELOG.md
- docs/reference/toloka.streaming.pipeline.Pipeline.md
- docs/reference/toloka.streaming.storage.BaseStorage.cleanup.md
- docs/reference/toloka.streaming.storage.BaseStorage.load.md
- docs/reference/toloka.streaming.storage.BaseStorage.save.md
- docs/reference/toloka.streaming.storage.JSONLocalStorage.cleanup.md
- docs/reference/toloka.streaming.storage.JSONLocalStorage.load.md
- docs/reference/toloka.streaming.storage.JSONLocalStorage.md
- docs/reference/toloka.streaming.storage.JSONLocalStorage.save.md
- docs/reference/toloka.streaming.storage.S3Storage.cleanup.md
- docs/reference/toloka.streaming.storage.S3Storage.load.md
- docs/reference/toloka.streaming.storage.S3Storage.save.md
- src/__version__.py
- src/client/__init__.py
- src/client/__init__.pyi
- src/client/primitives/retry.py
- src/streaming/pipeline.py
- src/streaming/pipeline.pyi
- src/streaming/storage.py
- src/streaming/storage.pyi
- tests/primitives/test_retries.py
- tests/streaming/test_pipeline.py
- tests/streaming/test_storage.py
0.1.21
-------------------
Fixes:
* Fixed maximum recursion depth exceptions
* Fixed `download_attachment`
> toloka-kit==0.1.21 release

- docs/index.md
Updated the minimum required Python version in docs
DOC-10822
> DOC-10822: Updated required Python version

- src/client/assignment.py
- src/client/project/template_builder/fields.py
- src/client/search_requests.py
- src/client/search_results.py
Updated docs in:
* search_requests.py
* search_results.py
Experimental **doc string generation function** used in search_results.py
> DOCSUP-31075-search-doc-updates

- src/client/__init__.py
- tests/pool/test_pool.py
- tests/test_project.py
- tests/test_skill.py
- tests/test_training.py
Change urls of prod and sandbox platforms in logging
> Add platform urls

- src/autoquality/optimizer.py
- src/client/filter.py
- src/client/pool/__init__.py
- tests/pool/conftest.py
- tests/pool/test_pool.py
- tests/test_filter.py
- tests/test_message_thread.py
`unstructure` pool wrappes filter in `FIlterAnd` and/or `FilterOr` to be good represented in UI
On top level:
`condition: Condition` -> `FilterAnd([FilterOr([condition])]`
`filter_or: FilterOr` -> `FilterAnd([filter_or])`
Also all `conditions: Condition` in `FilterAnd` wrapped in `FilterOr`
> Fix aq filters

- CHANGELOG.md
- misc/stubmaker/src/tk_stubgen/util.py
- misc/stubmaker/src/tk_stubgen/viewers/markdown_viewer.py
- src/client/__init__.py
- src/client/actions.py
- src/client/pool/mixer_config.py
- src/client/primitives/base.py
- src/client/primitives/retry.py
- src/client/project/template_builder/helpers.py
- src/client/project/view_spec.py
- src/client/skill.py
- src/client/task_suite.py
- src/client/training.py
- src/client/user_bonus.py
- src/metrics/jupyter_dashboard.py
Fixed some bugs in docstrings adn documentation generation.
> Fix documentation issues

- src/client/filter.py
- src/client/primitives/operators.py
- tests/primitives/test_operator.py
- tests/test_filter.py
Condition invertion is only inversion of operator
Complex filter invertion is processed according to [De Morgan's laws](https://en.wikipedia.org/wiki/De_Morgan%27s_laws)
Support inversion `~` logic operator  for filters
> Add filters inversion

- src/client/exceptions.py
- tests/test_exceptions.py
Change `__str__` generated by attrs to friendly one
> Make api exceptions friendly

- src/client/filter.py
- tests/pool/test_pool.py
Add new profile category filter: verified filter
> Add verified filter

- src/client/filter.py
- src/client/pool/__init__.py
- tests/pool/test_pool.py
- tests/test_filter.py
- tests/test_message_thread.py
Fix unwanted filters wrapping
In case of verified languages conditions schematically should be: 
`FilterAnd(..., FilterOr(FilterAnd(Language, Skill)),...)`
> Fix filter unstructure

- CHANGELOG.md
- src/__version__.py
> 1.0.1 release

- src/__version__.py
> 1.1.0.post1 release

- src/client/aggregation.py
Added a short notice about the limitations of the method when using the Dawid-Skene aggregation
TOLOBUGS-2135
> Added a notice mentioned in TOLOBUGS-2135

- .github/workflows/tests.yml
Docs team uses YFM of 1.31.1 version so we should use the same version in our tests
> Use 1.31.1 YFM version

- src/client/__init__.py
- src/client/assignment.py
- src/client/message_thread.py
- src/client/operations.py
- src/client/owner.py
- src/client/pool/__init__.py
- src/client/pool/mixer_config.py
- src/client/primitives/infinite_overlap.py
- src/client/project/__init__.py
- src/client/project/template_builder/conditions.py
- src/client/project/template_builder/fields.py
- src/client/project/view_spec.py
- src/client/search_results.py
- src/client/skill.py
- src/client/task.py
- src/client/task_suite.py
- src/client/training.py
- src/client/user_bonus.py
- src/client/user_restriction.py
- src/client/webhook_subscription.py
- src/metrics/metrics.py
- src/metrics/pool_metrics.py
- Examples with russian changed
- Dash added to every "read-only"
- "Requester's" mentioning removed (Requester's guide).
- True and False wrapped with quotas.
> DOCSUP-39590-doc-fixes

- docs/en/_includes/toloka-kit-reference-toc.yaml
Backsync changes from Toloka/docs
> Unhide async client methods in documentation

- CHANGELOG.md
- src/__version__.py
toloka-kit==1.1.2 pre-release changes
> 1.1.2 release

- CHANGELOG.md
- setup.py
- src/__version__.py
1.1.3 release change log and version bump
> 1.1.3 release

- tests/streaming/test_pipeline.py
Current implementation of the `toloka.streaming.Pipeline` save/load does not preserve cross references in the saved objects. Added failing test to mark this problem.
> Added failing pipeline save/load test

- src/client/project/template_builder/conditions.py
Removed outdated links to 'dita' files (no longer used), fixed formatting
Removed outdated links to 'dita' files (no longer used), fixed formatting
> Fixed text and links in conditions.py

- src/autoquality/optimizer.py
- src/client/filter.py
- src/client/project/template_builder/helpers.py
- src/metrics/jupyter_dashboard.py
- src/metrics/metrics.py
- src/metrics/pool_metrics.py
- src/streaming/locker.py
Fixed several code samples with broken syntax
> Fixes for code samples in the docs

- src/client/analytics_request.py
Fixed description for 'SubmittedAssignmentsCountPoolAnalytics'
TOLOKAKIT-954
> Docs fixes for TOLOKAKIT-954

- src/async_client/client.py
- src/client/__init__.py
- tests/conftest.py
- tests/test_client.py
> Add verify arg to TolokaClient init

- src/client/filter.py
Added description for OSFamily class attributes
TOLOBUGS-2359
> Added description for OSFamily class attributes

- CHANGELOG.md
- src/__version__.py
> 1.1.4 release

- tests/slow_tests/test_retries.py
Additional test case for retries
> Added socket server with chunked transfer encoding to retry tests

- src/client/__init__.py
- src/client/app/__init__.py
> DOCSUP-44195-app-docs-examples

- README.md
Removed the unnecessary `.html` parts from the links to the docs. Redirects are fixed now, but just in case, there's no need to have them.
> Updated links in the README.md file

- src/client/__init__.py
- src/client/attachment.py
- src/client/batch_create_results.py
- src/client/clone_results.py
- src/client/error_codes.py
- src/client/exceptions.py
- src/client/message_thread.py
> DOCSUP-45760-message-threads-docs-update

- setup.py
- src/async_client/client.py
- src/client/__init__.py
- src/client/exceptions.py
- src/client/primitives/adapters.py
- src/client/primitives/retry.py
- tests/primitives/test_retry.py
- tests/slow_tests/conftest.py
- tests/slow_tests/test_async.py
- tests/slow_tests/test_retries.py
- tox.ini
RetryingOverURLLibRetry logic overhaul to correctly match urllib3 retrying behavior
> Refactor RetryingOverURLLibRetry to match urllib3 retrying behavior

- src/client/__init__.py
Add ApiKey support for SSO users
Add ApiKey support for SSO users
> Support ApiKey auth

- src/client/primitives/parameter.py
Update 'operation_id' description
TOLOBUGS-2636
> Update 'operation_id' description

- src/client/__init__.py
- src/client/user.py
- src/client/user_bonus.py
- src/client/user_restriction.py
> DOCSUP-49901-user-docs-update

- docs/en/_includes/toloka-kit-toc.yaml
Fixed incorrect entries in the docs menu
> Fixed incorrect docs menu

- src/client/__init__.py
- src/client/actions.py
- src/client/aggregation.py
- src/client/analytics_request.py
- src/client/app/__init__.py
- src/client/assignment.py
- src/client/attachment.py
- src/client/batch_create_results.py
- src/client/clone_results.py
- src/client/conditions.py
- src/metrics/metrics.py
> DOCSUP-51576 Examples added

- src/client/__init__.py
- tests/pool/test_pool.py
Added `tier` parameter to `TolokaClient.create_pool`
> Add tier parameters to create_pool

- src/client/__init__.py
- tests/pool/test_pool.py
Rename query parameter from `tier` to `storage_key`
> Fix create_pool tier parameter

- CHANGELOG.md
- src/__version__.py
> toloka-kit==1.2.1

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Updating CLA links for external contributors.
> Change CLA
